name: AntiDeepslateESP
version: ${project.version}
main: me.nghiadark.antideepslateesp.AntiDeepslateESP
author: nghiadark
api-version: '1.21'
depend: [ProtocolLib]

commands:
  antideepslateesp:
    description: AntiDeepslateESP main command
    aliases: [adsesp]
    permission: antideepslateesp.reload

permissions:
  antideepslateesp.reload:
    description: Reload the plugin configuration
    default: op
